import { Station } from './types'

export const stations: Station[] = [
  // Pacifica Network
  {
    id: 'kpfa',
    name: 'KPFA',
    slug: 'kpfa',
    callSign: 'KPFA',
    frequency: '94.1 FM',
    location: 'Berkeley, CA',
    description: 'Free speech radio since 1949. News, public affairs, music, and arts programming.',
    streamUrl: 'https://stream.kpfa.org/kpfa_64',
    website: 'https://kpfa.org',
    network: 'Pacifica',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'kpfk',
    name: 'KPFK',
    slug: 'kpfk',
    callSign: 'KPFK',
    frequency: '90.7 FM',
    location: 'Los Angeles, CA',
    description: 'Progressive talk radio serving Southern California.',
    streamUrl: 'https://stream.kpfk.org/kpfk_64',
    website: 'https://kpfk.org',
    network: 'Pacifica',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'kpft',
    name: 'KPFT',
    slug: 'kpft',
    callSign: 'KPFT',
    frequency: '90.1 FM',
    location: 'Houston, TX',
    description: 'Community radio for Houston and the Gulf Coast.',
    streamUrl: 'https://stream.kpft.org/kpft_64',
    website: 'https://kpft.org',
    network: 'Pacifica',
    timezone: 'America/Chicago',
  },
  {
    id: 'wbai',
    name: 'WBAI',
    slug: 'wbai',
    callSign: 'WBAI',
    frequency: '99.5 FM',
    location: 'New York, NY',
    description: 'Listener-sponsored radio in New York City.',
    streamUrl: 'https://stream.wbai.org/wbai_64',
    website: 'https://wbai.org',
    network: 'Pacifica',
    timezone: 'America/New_York',
  },
  {
    id: 'wpfw',
    name: 'WPFW',
    slug: 'wpfw',
    callSign: 'WPFW',
    frequency: '89.3 FM',
    location: 'Washington, DC',
    description: 'Jazz and justice radio for the DC metro area.',
    streamUrl: 'https://stream.wpfw.org/wpfw_64',
    website: 'https://wpfw.org',
    network: 'Pacifica',
    timezone: 'America/New_York',
  },
  // Other community stations
  {
    id: 'kexp',
    name: 'KEXP',
    slug: 'kexp',
    callSign: 'KEXP',
    frequency: '90.3 FM',
    location: 'Seattle, WA',
    description: 'Where the music matters. Indie, alternative, and eclectic music.',
    streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    website: 'https://kexp.org',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'wfmu',
    name: 'WFMU',
    slug: 'wfmu',
    callSign: 'WFMU',
    frequency: '91.1 FM',
    location: 'Jersey City, NJ',
    description: 'Freeform radio - the longest running freeform station in the US.',
    streamUrl: 'https://stream0.wfmu.org/freeform-128k',
    website: 'https://wfmu.org',
    timezone: 'America/New_York',
  },
  {
    id: 'kcrw',
    name: 'KCRW',
    slug: 'kcrw',
    callSign: 'KCRW',
    frequency: '89.9 FM',
    location: 'Santa Monica, CA',
    description: 'Music, news, and culture from Southern California.',
    streamUrl: 'https://kcrw.streamguys1.com/kcrw_192k_mp3_on_air',
    website: 'https://kcrw.com',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'kutx',
    name: 'KUTX',
    slug: 'kutx',
    callSign: 'KUTX',
    frequency: '98.9 FM',
    location: 'Austin, TX',
    description: 'Austin\'s music radio - local and independent.',
    streamUrl: 'https://kut.streamguys1.com/kutx-free',
    website: 'https://kutx.org',
    timezone: 'America/Chicago',
  },
  {
    id: 'wxpn',
    name: 'WXPN',
    slug: 'wxpn',
    callSign: 'WXPN',
    frequency: '88.5 FM',
    location: 'Philadelphia, PA',
    description: 'Member-supported music discovery from the University of Pennsylvania.',
    streamUrl: 'https://wxpnhi.xpn.org/xpnhi',
    website: 'https://xpn.org',
    timezone: 'America/New_York',
  },
]

export function getStation(slug: string): Station | undefined {
  return stations.find(s => s.slug === slug)
}

export function getStationsByNetwork(network: string): Station[] {
  return stations.filter(s => s.network === network)
}
