import { Station } from './types'

export const stations: Station[] = [
  // === BAY AREA ===
  {
    id: 'kpfa',
    name: 'KPFA',
    slug: 'kpfa',
    callSign: 'KPFA',
    frequency: '94.1 FM',
    location: 'Berkeley, CA',
    description: 'Free speech radio since 1949. News, public affairs, and arts.',
    streamUrl: 'https://streams.kpfa.org:8443/kpfa',
    website: 'https://kpfa.org',
    donateUrl: 'https://kpfa.org/donate/',
    logoUrl: 'https://kpfa.org/wp-content/uploads/2020/03/KPFA-Logo-300x300.png',
    network: 'Pacifica',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 37.8716, lng: -122.2727 },
  },
  {
    id: 'kalx',
    name: 'KALX',
    slug: 'kalx',
    callSign: 'KALX',
    frequency: '90.7 FM',
    location: 'Berkeley, CA',
    description: 'Freeform college radio from UC Berkeley. Eclectic and adventurous.',
    streamUrl: 'https://stream.kalx.berkeley.edu:8443/kalx-128.mp3',
    website: 'https://kalx.berkeley.edu',
    donateUrl: 'https://kalx.berkeley.edu/support/',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 37.8719, lng: -122.2585 },
  },
  {
    id: 'kqed',
    name: 'KQED',
    slug: 'kqed',
    callSign: 'KQED',
    frequency: '88.5 FM',
    location: 'San Francisco, CA',
    description: 'NPR news and information for the Bay Area.',
    streamUrl: 'https://streams.kqed.org/kqedradio',
    website: 'https://kqed.org',
    donateUrl: 'https://www.kqed.org/donate',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },

  // === LOS ANGELES ===
  {
    id: 'kcrw',
    name: 'KCRW',
    slug: 'kcrw',
    callSign: 'KCRW',
    frequency: '89.9 FM',
    location: 'Santa Monica, CA',
    description: 'Eclectic music, NPR news, and culture from LA.',
    streamUrl: 'https://kcrw.streamguys1.com/kcrw_192k_mp3_e24',
    website: 'https://kcrw.com',
    donateUrl: 'https://www.kcrw.com/give',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 34.0195, lng: -118.4912 },
  },

  // === TEXAS ===
  {
    id: 'kutx',
    name: 'KUTX',
    slug: 'kutx',
    callSign: 'KUTX',
    frequency: '98.9 FM',
    location: 'Austin, TX',
    description: 'The Austin music experience. Local and indie music.',
    streamUrl: 'https://streams.kut.org/4428_192.mp3',
    website: 'https://kutx.org',
    donateUrl: 'https://kutx.org/support/',
    timezone: 'America/Chicago',
    coordinates: { lat: 30.2672, lng: -97.7431 },
  },

  // === MIDWEST ===
  {
    id: 'wbez',
    name: 'WBEZ',
    slug: 'wbez',
    callSign: 'WBEZ',
    frequency: '91.5 FM',
    location: 'Chicago, IL',
    description: "Chicago's NPR news source. Home of This American Life.",
    streamUrl: 'https://stream.wbez.org/wbez128.mp3',
    website: 'https://wbez.org',
    donateUrl: 'https://www.wbez.org/donate',
    timezone: 'America/Chicago',
    coordinates: { lat: 41.8781, lng: -87.6298 },
  },
  {
    id: 'thecurrent',
    name: 'The Current',
    slug: 'thecurrent',
    callSign: 'KCMP',
    frequency: '89.3 FM',
    location: 'Minneapolis, MN',
    description: 'Minnesota Public Radio. Where the music matters.',
    streamUrl: 'https://current.stream.publicradio.org/kcmp.mp3',
    website: 'https://thecurrent.org',
    donateUrl: 'https://support.mpr.org/thecurrent',
    timezone: 'America/Chicago',
    coordinates: { lat: 44.9778, lng: -93.2650 },
  },

  // === PACIFIC NORTHWEST ===
  {
    id: 'kexp',
    name: 'KEXP',
    slug: 'kexp',
    callSign: 'KEXP',
    frequency: '90.3 FM',
    location: 'Seattle, WA',
    description: 'Where the music matters. Indie and eclectic.',
    streamUrl: 'https://kexp.streamguys1.com/kexp160.aac',
    website: 'https://kexp.org',
    donateUrl: 'https://www.kexp.org/donate/',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 47.6062, lng: -122.3321 },
  },

  // === SOUTHEAST ===
  {
    id: 'wdvx',
    name: 'WDVX',
    slug: 'wdvx',
    callSign: 'WDVX',
    frequency: '89.9 FM',
    location: 'Knoxville, TN',
    description: 'Roots radio from East Tennessee. Americana and bluegrass.',
    streamUrl: 'https://wdvx.streamguys1.com/live',
    website: 'https://wdvx.com',
    donateUrl: 'https://wdvx.com/support/',
    timezone: 'America/New_York',
    coordinates: { lat: 35.9606, lng: -83.9207 },
  },

  // === NEW ORLEANS ===
  {
    id: 'wwoz',
    name: 'WWOZ',
    slug: 'wwoz',
    callSign: 'WWOZ',
    frequency: '90.7 FM',
    location: 'New Orleans, LA',
    description: "New Orleans' jazz and heritage station.",
    streamUrl: 'https://wwoz-sc.streamguys1.com/wwoz-hi.mp3',
    website: 'https://wwoz.org',
    donateUrl: 'https://www.wwoz.org/donate',
    timezone: 'America/Chicago',
    coordinates: { lat: 29.9511, lng: -90.0715 },
  },

  // === NORTHEAST ===
  {
    id: 'wfmu',
    name: 'WFMU',
    slug: 'wfmu',
    callSign: 'WFMU',
    frequency: '91.1 FM',
    location: 'Jersey City, NJ',
    description: 'Freeform radio. Longest running freeform station in the US.',
    streamUrl: 'https://stream0.wfmu.org/freeform-128k',
    website: 'https://wfmu.org',
    donateUrl: 'https://wfmu.org/donate',
    timezone: 'America/New_York',
    coordinates: { lat: 40.7282, lng: -74.0776 },
  },
  {
    id: 'wfuv',
    name: 'WFUV',
    slug: 'wfuv',
    callSign: 'WFUV',
    frequency: '90.7 FM',
    location: 'Bronx, NY',
    description: 'Public radio from Fordham. Adult album alternative.',
    streamUrl: 'https://onair.wfuv.org/onair-hi',
    website: 'https://wfuv.org',
    donateUrl: 'https://wfuv.org/support',
    timezone: 'America/New_York',
    coordinates: { lat: 40.8612, lng: -73.8883 },
  },
  {
    id: 'wnyc',
    name: 'WNYC',
    slug: 'wnyc',
    callSign: 'WNYC',
    frequency: '93.9 FM',
    location: 'New York, NY',
    description: "New York's flagship public radio station.",
    streamUrl: 'https://stream.wnyc.org/wnycfm',
    website: 'https://wnyc.org',
    donateUrl: 'https://www.wnyc.org/donate/',
    timezone: 'America/New_York',
    coordinates: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: 'wqxr',
    name: 'WQXR',
    slug: 'wqxr',
    callSign: 'WQXR',
    frequency: '105.9 FM',
    location: 'New York, NY',
    description: "New York's classical music station.",
    streamUrl: 'https://stream.wqxr.org/wqxr',
    website: 'https://wqxr.org',
    donateUrl: 'https://www.wqxr.org/donate/',
    timezone: 'America/New_York',
    coordinates: { lat: 40.7589, lng: -73.9851 },
  },

  // === PHILADELPHIA ===
  {
    id: 'wxpn',
    name: 'WXPN',
    slug: 'wxpn',
    callSign: 'WXPN',
    frequency: '88.5 FM',
    location: 'Philadelphia, PA',
    description: 'Adult album alternative from UPenn.',
    streamUrl: 'https://wxpnhi.xpn.org/xpnhi',
    website: 'https://xpn.org',
    donateUrl: 'https://xpn.org/support/',
    timezone: 'America/New_York',
    coordinates: { lat: 39.9526, lng: -75.1652 },
  },

  // === NATIONAL ===
  {
    id: 'npr',
    name: 'NPR Live',
    slug: 'npr',
    callSign: 'NPR',
    frequency: 'National',
    location: 'Washington, DC',
    description: 'National Public Radio live program stream.',
    streamUrl: 'https://npr-ice.streamguys1.com/live.mp3',
    website: 'https://npr.org',
    donateUrl: 'https://www.npr.org/donations/support',
    timezone: 'America/New_York',
    coordinates: { lat: 38.9072, lng: -77.0369 },
  },

  // === INTERNET RADIO ===
  {
    id: 'somafm',
    name: 'SomaFM Groove Salad',
    slug: 'somafm',
    callSign: 'SOMA',
    frequency: 'Internet',
    location: 'San Francisco, CA',
    description: 'Ambient/downtempo. Listener-supported internet radio.',
    streamUrl: 'https://ice1.somafm.com/groovesalad-128-mp3',
    website: 'https://somafm.com/groovesalad/',
    donateUrl: 'https://somafm.com/support/',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },
  {
    id: 'radioparadise',
    name: 'Radio Paradise',
    slug: 'radioparadise',
    callSign: 'RP',
    frequency: 'Internet',
    location: 'Paradise, CA',
    description: 'Eclectic DJ-curated music. No ads, no filler.',
    streamUrl: 'https://stream.radioparadise.com/aac-320',
    website: 'https://radioparadise.com',
    donateUrl: 'https://radioparadise.com/supporter',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 39.7596, lng: -121.6219 },
  },
  {
    id: 'nts',
    name: 'NTS Radio',
    slug: 'nts',
    callSign: 'NTS',
    frequency: 'Internet',
    location: 'London, UK',
    description: 'Underground music from London and beyond.',
    streamUrl: 'https://stream-relay-geo.ntslive.net/stream',
    website: 'https://nts.live',
    donateUrl: 'https://www.nts.live/supporters',
    timezone: 'Europe/London',
    coordinates: { lat: 51.5074, lng: -0.1278 },
  },
  {
    id: 'jazzfm',
    name: 'Jazz FM',
    slug: 'jazzfm',
    callSign: 'JAZZ',
    frequency: 'Internet',
    location: 'London, UK',
    description: 'Jazz, soul, and blues from the UK.',
    streamUrl: 'https://pureplay.cdnstream1.com/6001_64.aac',
    website: 'https://jazzfm.com',
    donateUrl: 'https://jazzfm.com',
    timezone: 'Europe/London',
    coordinates: { lat: 51.5155, lng: -0.1419 },
  },
]

export function getStation(slug: string): Station | undefined {
  return stations.find(s => s.slug === slug)
}

export function getStationsByLocation(state: string): Station[] {
  return stations.filter(s => s.location.includes(state))
}
